import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "./context/userContext";
import { QuizzesContextProvider } from "./context/quizzesContext";

const roboto = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} flex flex-col items-center bg-neutral-950 text-neutral-50`}
      >
        <UserContextProvider>
          <QuizzesContextProvider>{children}</QuizzesContextProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
